name: puntgpt_nick
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  provider: ^6.1.5+1
  dio: ^5.9.0
  flutter_svg: ^2.2.1
  go_router: ^16.2.4
  flutter_animate: ^4.5.2
  dropdown_button2: ^2.3.9
  intl: ^0.20.2
  flutter_staggered_grid_view: ^0.7.0
  animate_do: ^4.2.0
  toastification: ^3.0.3
  modal_side_sheet: ^0.0.1
  dartz: ^0.10.1
  shared_preferences: ^2.5.4
  pretty_dio_logger: ^1.4.0
  pinput: ^6.0.1
  connectivity_plus: ^7.0.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          style: normal
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700

    - family: ChangaOne
      fonts:
        - asset: assets/fonts/ChangaOne-Regular.ttf
